version: '3.8'

services:
  app:
    #image: d2ddeveloper2/python_websocket_message-app:latest
    platform: linux/amd64
    build: .
    ports:
      - "5010:5010"
    environment:
      - DATABASE_URL=mysql+pymysql://root:Test%40123456@db/MessengerDB
      - SECRET_KEY=dev-secret-key
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Test@123456
      MYSQL_DATABASE: MessengerDB
      MYSQL_PASSWORD: Test@123456
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_port: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
